export const SampleAds = [
    {
        id: '43452322',
        userId: 'dsdfsf',
        createDate: new Date(),
        data: {
            title: 'Вакансия 1',
            field: 'it',
            experience: '3 year',
            schedule: 'asda',
            sex: 'male',
            education: 'university',
            language: 'english',
            salary: '150000',
            photo: 'https://yt3.ggpht.com/ytc/AAUvwnh-6ik6sGBI4-fHDxQ1VvID-xmgitMfwUDrs6kxrYk=s900-c-k-c0x00ffffff-no-rj',
        },
    },
    {
        id: '434dfg4',
        userId: 'dsdfsf',
        createDate: new Date(),
        data: {
            title: 'Вакансия 2',
            field: 'manager',
            experience: '3 year',
            schedule: 'asdfsgda',
            sex: 'female',
            education: 'university',
            language: 'russian',
            salary: '100000',
            photo: 'https://i.pinimg.com/originals/97/17/e5/9717e5cf185c1e7dd55196a882903601.jpg',
        },
    },
    {
        id: '43434rgd',
        userId: 'dsdfsf',
        createDate: new Date(),
        data: {
            title: 'Вакансия 3',
            field: 'manager',
            experience: '3 year',
            schedule: 'asdfsgda',
            sex: 'female',
            education: 'university',
            language: 'russian',
            salary: '100000',
            photo: 'https://phonoteka.org/uploads/posts/2021-05/1622467118_16-phonoteka_org-p-vselennaya-kosmos-art-krasivo-18.jpg',
        },
    },
    {
        id: '4er34345',
        userId: 'dsdfsf',
        createDate: new Date(),
        data: {
            title: 'Вакансия 4',
            field: 'engineer',
            experience: '1 year',
            schedule: 'asdfsgda',
            sex: 'female',
            education: 'university',
            language: 'russian',
            salary: '100000',
            photo: 'https://a.d-cd.net/3a66326s-1920.jpg',
        },
    },
]
